# Generated by Django 5.0.7 on 2024-10-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
